# -*- coding: utf-8 -*-
"""Assignemny.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EsLVC5nfpGv96R09s9Y3N3Yf_dBdjH0b
"""

"""
Self-Pruning Neural Network on CIFAR-10
========================================
Implements a feed-forward MLP with learnable gate parameters that
encourage sparsity via L1 regularisation on sigmoid gate values.

Assignment: Tredence Analytics – Self-Pruning Neural Network Challenge
"""
!pip install torch torchvision matplotlib

import math
import multiprocessing

import matplotlib
matplotlib.use("Agg")          # headless – no display required
import matplotlib.pyplot as plt
import torch
import torch.nn as torch_nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms


# ══════════════════════════════════════════════════════════════════════
#  PART 1 – PrunableLinear Layer
# ══════════════════════════════════════════════════════════════════════

class PrunableLinear(torch_nn.Module):
    """
    A drop-in replacement for nn.Linear that attaches a learnable scalar
    gate to every weight element.

    Forward pass:
        gates        = sigmoid(gate_scores)          ∈ (0, 1)
        pruned_weight = weight * gates               (element-wise)
        output        = pruned_weight @ x^T + bias

    Because sigmoid is differentiable everywhere, gradients flow cleanly
    through both `weight` and `gate_scores` during back-propagation.
    """

    def __init__(self, in_features: int, out_features: int):
        super().__init__()
        self.in_features  = in_features
        self.out_features = out_features

        # ── Standard parameters ──────────────────────────────────────
        self.weight = torch_nn.Parameter(torch.Tensor(out_features, in_features))
        self.bias   = torch_nn.Parameter(torch.Tensor(out_features))

        # ── Gate scores (same shape as weight) ───────────────────────
        # Registered as a Parameter so the optimiser updates them too.
        # Initialised with small normal noise → sigmoid ≈ 0.5 at start.
        self.gate_scores = torch_nn.Parameter(torch.Tensor(out_features, in_features))

        self._reset_parameters()

    # ------------------------------------------------------------------
    def _reset_parameters(self):
        # Standard Kaiming uniform init for the weight matrix
        torch_nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))

        # Bias init matching nn.Linear's default
        fan_in, _ = torch_nn.init._calculate_fan_in_and_fan_out(self.weight)
        bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
        torch_nn.init.uniform_(self.bias, -bound, bound)

        # Gate scores: small normal → sigmoid(score) ≈ 0.5 initially
        torch_nn.init.normal_(self.gate_scores, mean=0.0, std=0.1)

    # ------------------------------------------------------------------
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Step 1 – convert raw scores to gates in (0, 1)
        gates = torch.sigmoid(self.gate_scores)

        # Step 2 – element-wise gate the weights
        pruned_weights = self.weight * gates

        # Step 3 – standard affine transform
        return F.linear(x, pruned_weights, self.bias)

    # ------------------------------------------------------------------
    def sparsity_info(self, threshold: float = 1e-2):
        """Return (n_pruned, n_total) for this layer."""
        with torch.no_grad():
            gates    = torch.sigmoid(self.gate_scores)
            n_pruned = int((gates < threshold).sum().item())
        return n_pruned, self.gate_scores.numel()


# ══════════════════════════════════════════════════════════════════════
#  PART 1 (cont.) – The Network
# ══════════════════════════════════════════════════════════════════════

class SelfPruningMLP(torch_nn.Module):
    """
    Three-layer MLP for CIFAR-10.
    Input: 3 × 32 × 32 = 3 072 features   Output: 10 classes
    All linear layers use PrunableLinear.
    """

    def __init__(self):
        super().__init__()
        self.flatten = torch_nn.Flatten()
        self.fc1 = PrunableLinear(3072, 512)
        self.fc2 = PrunableLinear(512,  256)
        self.fc3 = PrunableLinear(256,   10)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.flatten(x)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

    def sparsity_level(self, threshold: float = 1e-2) -> float:
        """Overall % of weight-gates that are below `threshold`."""
        total_pruned = total_weights = 0
        for m in self.modules():
            if isinstance(m, PrunableLinear):
                p, t = m.sparsity_info(threshold)
                total_pruned  += p
                total_weights += t
        return 100.0 * total_pruned / total_weights if total_weights else 0.0


# ══════════════════════════════════════════════════════════════════════
#  PART 2 – Sparsity Regularisation Loss
# ══════════════════════════════════════════════════════════════════════

def calculate_sparsity_loss(model: SelfPruningMLP) -> torch.Tensor:
    """
    L1 penalty on all gate values.

    SparsityLoss = Σ_layers Σ_i sigmoid(gate_scores_i)

    Why L1 encourages sparsity
    ──────────────────────────
    The L1 norm penalises every gate proportionally to its value.
    Unlike L2, whose gradient vanishes near zero, L1 applies a constant
    sub-gradient of ±1 regardless of magnitude.  This constant "pull
    toward zero" is strong enough to drive small, unimportant gates all
    the way to zero, while large gates (that carry useful signal) resist
    the penalty because the classification loss still rewards them.
    The result is a bimodal distribution: many gates collapse to ≈ 0
    (pruned) and a few remain large (kept).
    """
    sparsity_loss = torch.tensor(0.0, device=next(model.parameters()).device)
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            # Gates are always positive, so L1 norm = sum of gate values
            sparsity_loss = sparsity_loss + torch.sum(torch.sigmoid(m.gate_scores))
    return sparsity_loss


# ══════════════════════════════════════════════════════════════════════
#  PART 3 – Training & Evaluation
# ══════════════════════════════════════════════════════════════════════

def train_and_eval(
    lambda_val: float,
    trainloader,
    testloader,
    device: torch.device,
    epochs: int = 10,
) -> tuple:
    """
    Train one SelfPruningMLP with the given λ, then evaluate it.

    Total Loss = CrossEntropyLoss + λ × SparsityLoss

    Returns
    -------
    model      : trained SelfPruningMLP
    accuracy   : float  – test accuracy (%)
    sparsity   : float  – % of gates < 1e-2 after training
    """
    print(f"\n{'━'*58}")
    print(f"  λ = {lambda_val}  |  epochs = {epochs}")
    print(f"{'━'*58}")

    model     = SelfPruningMLP().to(device)
    criterion = torch_nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=1e-3)

    # ── Training loop ──────────────────────────────────────────────
    for epoch in range(epochs):
        model.train()
        running_loss = 0.0

        for i, (inputs, labels) in enumerate(trainloader):
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()

            outputs = model(inputs)

            # Classification loss
            cls_loss  = criterion(outputs, labels)

            # Sparsity regularisation (L1 on all gates)
            spar_loss = calculate_sparsity_loss(model)

            # Combined loss
            loss = cls_loss + lambda_val * spar_loss

            loss.backward()      # gradients flow through weight AND gate_scores
            optimizer.step()

            running_loss += loss.item()
            if i % 200 == 199:
                print(
                    f"  epoch {epoch+1:>2}/{epochs}  "
                    f"step {i+1:>5d}  "
                    f"loss {running_loss / 200:.4f}  "
                    f"sparsity {model.sparsity_level():.1f}%"
                )
                running_loss = 0.0

    # ── Evaluation ─────────────────────────────────────────────────
    model.eval()
    correct = total = 0
    with torch.no_grad():
        for inputs, labels in testloader:
            inputs, labels = inputs.to(device), labels.to(device)
            _, predicted   = torch.max(model(inputs), 1)
            total   += labels.size(0)
            correct += (predicted == labels).sum().item()

    accuracy = 100.0 * correct / total
    sparsity = model.sparsity_level(threshold=1e-2)

    print(f"\n  ✓  Test Accuracy  : {accuracy:.2f}%")
    print(f"  ✓  Sparsity Level : {sparsity:.2f}%  (gates < 1e-2)")

    return model, accuracy, sparsity


# ══════════════════════════════════════════════════════════════════════
#  Plotting helpers
# ══════════════════════════════════════════════════════════════════════

def get_all_gates(model: SelfPruningMLP) -> list:
    """Collect every gate value (as a Python float) across all layers."""
    gates = []
    with torch.no_grad():
        for m in model.modules():
            if isinstance(m, PrunableLinear):
                gates.extend(
                    torch.sigmoid(m.gate_scores).flatten().cpu().tolist()
                )
    return gates


def plot_gate_distribution(model: SelfPruningMLP, lambda_val: float,
                           path: str = "gate_distribution.png") -> None:
    """
    Histogram of all gate values for the given model.
    A successful pruning run shows a large spike near 0 and a smaller
    cluster of surviving gates clustered away from 0.
    """
    gates = get_all_gates(model)

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.hist(gates, bins=80, color="#3B82F6", edgecolor="white",
            linewidth=0.3, alpha=0.88)
    ax.set_yscale("log")                # log-scale reveals the non-zero tail
    ax.set_xlim(0, 1)
    ax.set_title(
        f"Distribution of Gate Values   (λ = {lambda_val})\n"
        f"Sparsity: {model.sparsity_level():.1f}%  |  "
        f"Total gates: {len(gates):,}",
        fontsize=12
    )
    ax.set_xlabel("Gate Value  [sigmoid output]", fontsize=11)
    ax.set_ylabel("Frequency  (log scale)",       fontsize=11)
    ax.axvline(0.01, color="red", linestyle="--", linewidth=1.2,
               label="Pruning threshold (0.01)")
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()
    print(f"  Saved → '{path}'")


def plot_accuracy_sparsity(results: list,
                           path: str = "accuracy_vs_sparsity.png") -> None:
    """Dual-axis bar chart: accuracy and sparsity vs λ."""
    labels     = [f"λ={r['lambda']}" for r in results]
    accuracies = [r["accuracy"] for r in results]
    sparsities = [r["sparsity"] for r in results]

    x   = list(range(len(labels)))
    fig, ax1 = plt.subplots(figsize=(9, 5))

    ax1.bar([i - 0.2 for i in x], accuracies, width=0.38,
            label="Test Accuracy (%)", color="#10B981", alpha=0.85)
    ax1.set_ylabel("Test Accuracy (%)", color="#10B981", fontsize=11)
    ax1.tick_params(axis="y", labelcolor="#10B981")
    ax1.set_ylim(0, 100)

    ax2 = ax1.twinx()
    ax2.bar([i + 0.2 for i in x], sparsities, width=0.38,
            label="Sparsity (%)", color="#F59E0B", alpha=0.85)
    ax2.set_ylabel("Sparsity (%)", color="#F59E0B", fontsize=11)
    ax2.tick_params(axis="y", labelcolor="#F59E0B")
    ax2.set_ylim(0, 100)

    ax1.set_xticks(x)
    ax1.set_xticklabels(labels, fontsize=11)
    ax1.set_title("Test Accuracy vs Sparsity Level across λ values", fontsize=12)

    h1, l1 = ax1.get_legend_handles_labels()
    h2, l2 = ax2.get_legend_handles_labels()
    ax1.legend(h1 + h2, l1 + l2, loc="upper left", fontsize=10)

    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()
    print(f"  Saved → '{path}'")


# ══════════════════════════════════════════════════════════════════════
#  Main
# ══════════════════════════════════════════════════════════════════════

def main():
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}\n")

    # ── CIFAR-10 data loaders ────────────────────────────────────────
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
    ])

    trainset = torchvision.datasets.CIFAR10(
        root="./data", train=True,  download=True, transform=transform)
    testset  = torchvision.datasets.CIFAR10(
        root="./data", train=False, download=True, transform=transform)

    trainloader = torch.utils.data.DataLoader(
        trainset, batch_size=64, shuffle=True,  num_workers=2)
    testloader  = torch.utils.data.DataLoader(
        testset,  batch_size=64, shuffle=False, num_workers=2)

    # ── Lambda sweep (low / medium / high) ──────────────────────────
    # λ=0        → no pruning pressure  (baseline)
    # λ=1e-5     → gentle pruning
    # λ=1e-4     → medium pruning
    # λ=1e-3     → strong pruning
    #
    # NOTE: We use the raw L1 sum as required by the assignment spec.
    # With ~1.7 M gates the sparsity term is already large, so even
    # λ=1e-5 applies meaningful pressure.
    lambda_values = [0.0, 1e-5, 1e-4, 1e-3]

    results    = []
    best_model = None          # we'll plot the gate dist for λ = 1e-4

    for lv in lambda_values:
        model, acc, spar = train_and_eval(
            lv, trainloader, testloader, device, epochs=10
        )
        results.append({"lambda": lv, "accuracy": acc, "sparsity": spar})
        if lv == 1e-4:
            best_model = model

    # ── Summary table ────────────────────────────────────────────────
    print("\n" + "═" * 52)
    print(f"  {'Lambda':<12} {'Test Acc (%)':>14} {'Sparsity (%)':>14}")
    print("═" * 52)
    for r in results:
        print(f"  {r['lambda']:<12.0e} {r['accuracy']:>14.2f} {r['sparsity']:>14.2f}")
    print("═" * 52)

    # ── Plots ────────────────────────────────────────────────────────
    print("\nSaving plots …")
    if best_model is not None:
        plot_gate_distribution(best_model, lambda_val=1e-4,
                               path="gate_distribution.png")
    plot_accuracy_sparsity(results, path="accuracy_vs_sparsity.png")
    print("\nAll done.")


if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()

from IPython.display import Image, display

print('Displaying gate_distribution.png:')
display(Image('gate_distribution.png'))

print('\nDisplaying accuracy_vs_sparsity.png:')
display(Image('accuracy_vs_sparsity.png'))